### ISSUE TITLE
Multiple TLVs with same tag get clobbered

### ISSUE THREAD

**Issue by mtihlenfield** [toumilov/python-ber-tlv#2]
Hi!

First of all, thanks for your work on this great library! It's been very useful to me.

I've found a bug in the parsing of data with multiple TLVs of the same tag, at the same level.

Take the following TLV string for example:
`c61890017e83010183018183010a83010b83010c83010d83010e`

This should parse out to something like this:
```
{
    198: [
        (144, b'~'), 
        (131, b'\x01'), 
        (131, b'\x81'), 
        (131, b'\n'), 
        (131, b'\x0b'), 
        (131, b'\x0c'), 
        (131, b'\r'), 
        (131, b'\x0e')
    ]
}
```

But the result actually ends up being:
```
>>> from ber_tlv.tlv import Tlv
>>> import binascii
>>> hex_tlv = "c61890017e83010183018183010a83010b83010c83010d83010e"
>>> Tlv.parse(binascii.unhexlify(hex_tlv), True)
{
    198: {
        144: b'~', 
        131: b'\x0e'
    }
}
```

This is due to the fact that `Tlv.parse` stores the result in a dictionary and doesn't check to see if the dictionary already has a key for the tag it's trying to add. I've been able to solve this for my purposes by modifying `Tlv.parse` to keep the result as a list of `(tag, value)` tuples, like so:

```
[
    (198: [
        (144, b'~'), 
        (131, b'\x01'), 
        (131, b'\x81'), 
        (131, b'\n'), 
        (131, b'\x0b'), 
        (131, b'\x0c'), 
        (131, b'\r'), 
        (131, b'\x0e')
    )
]
```

New tags/value pairs are added to the result by doing `res.append((tag, value))` rather than `res[tag] = value`.

I'd be glad to post a pull request for this if you'd be interested, but unfortunately this change would break any code expecting `Tlv.parse` to return a dict, and I'm not sure how to fix this issue without that breakage

I'm testing this on:
- Ubuntu 20.04
- Python 3.8.10
-  ber_tlv 0.0.2

**Comment by toumilov** [comment]
Hi Matt,

Nice to know that I'm doing something useful for community :)
Regarding the problem, Python dictionaries do not support duplicate keys. One of the options I have in mind is adding a list of items under the key that has more than one value:

```
{
    198: {
        144: b'~', 
        131: [b'\x01', b'\x81', b'\n', b'\x0b', b'\x0c', b'\r', b'\x0e']
    }
}
```
Would it be acceptable for your needs?

**Comment by toumilov** [comment]
Fixed: https://github.com/toumilov/python-ber-tlv/commit/cbea9b6a160d10b4b4685f8c69babb01e92a6ff7

**Comment by mtihlenfield** [comment]
The only concern I have with this is that it doesn't necessarily preserve the order of objects. If you have a TLV string where the tags are arranged in this order:

```
141
131
131
131
141
131
```
The result would be:

```
{
    141: [...],
    131: [...]
}
```
and there would be no way to know, for example, that the last `131` tag actually came right after the last `141` tag rather than being grouped together with the other `131` tags.

This would mean that the solution doesn't work for my use case, but I'm not totally sure if (according to the spec) order is actually supposed to matter in BER-TLVs

**Comment by toumilov** [comment]
I believe element ordering is out of BER-TLV standard scope.
I've raised a new ticket for element ordering: https://github.com/toumilov/python-ber-tlv/issues/3
Will try to find some time to get it done :)

**Comment by mtihlenfield** [comment]
Thanks for addressing this!
