### ISSUE TITLE
if tag ends with 00 it gets trimmed 

### ISSUE THREAD

**Issue by mightyGi** [toumilov/python-ber-tlv#5]
Hi, excellent lib/repo.
when I called something like:
appID = b"app1231111111111"
Tlv.hexify_bytes(Tlv.build({**0xDFA300**:appID}))
the results was **DFA3**1061707031323331313131313131313131 , instead of **DFA300**1061707031323331313131313131313131

I don't know if this is a bug or by design (can't Tags end with 00?)

**Comment by toumilov** [comment]
Thanks for noticing this. Indeed, this is a bug.
Fixed in [version 0.0.6](https://pypi.org/project/ber-tlv/0.0.6/)
Update local version by `pip3 install ber-tlv --upgrade`
